//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        public int IDGioHang { get; set; }
        public Nullable<int> IDKhachHang { get; set; }
        public string IDSach { get; set; }
        public Nullable<int> SoLuongDat { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
