//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.GIOHANGs = new HashSet<GIOHANG>();
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
        }
    
        public string IDSach { get; set; }
        public string TenSach { get; set; }
        public string TacGia { get; set; }
        public string IDTheLoai { get; set; }
        public string NhaXuatBan { get; set; }
        public Nullable<int> NamXuatBan { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public string AnhSach { get; set; }
        public string MoTa { get; set; }
    
        public virtual THELOAI THELOAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
    }
}
